CREATE TABLE IF NOT EXISTS CONCLUSION_TEMPLATES
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id BIGINT                                  NOT NULL,
    positive_text    VARCHAR                                 NOT NULL,
    negative_text    VARCHAR                                 NOT NULL,
    CONSTRAINT pk_conclusionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_CONCLUSION_TEMPLATES UNIQUE (document_type_id)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_HEADERS_TEMPLATES
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id BIGINT                                  NOT NULL,
    division_type    VARCHAR                                 NOT NULL,
    division         VARCHAR                                 NOT NULL,
    address          VARCHAR,
    certificate      VARCHAR,
    contacts         VARCHAR,
    CONSTRAINT pk_documentHeaderTemplate PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id      BIGINT                                  NOT NULL,
    equipment_type_id     BIGINT                                  NOT NULL,
    title                 VARCHAR                                 NOT NULL,
    subtitle              VARCHAR                                 NOT NULL,
    equipment_text        VARCHAR                                 NOT NULL,
    installation_location VARCHAR                                 NOT NULL,
    city                  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_pageTitleTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PAGE_TITLE_TEMPLATES UNIQUE (document_type_id, equipment_type_id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLE_TEMPLATES_DOCUMENT_HEADERS
(
    page_title_template_id BIGINT,
    document_header_id     BIGINT,
    CONSTRAINT pk_page_title_templates_of_document_header PRIMARY KEY (page_title_template_id, document_header_id)
);

CREATE TABLE IF NOT EXISTS REPORT_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id  BIGINT                                  NOT NULL,
    equipment_type_id BIGINT                                  NOT NULL,
    page_title_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_REPORT_TEMPLATES UNIQUE (document_type_id, equipment_type_id),
    CONSTRAINT FK_REPORT_TEMPLATES_ON_PAGE_TITLE_TEMPLATES
        FOREIGN KEY (page_title_id) REFERENCES page_title_templates (id)
);

CREATE TABLE IF NOT EXISTS SECTION_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number  INTEGER                                 NOT NULL,
    section_name       VARCHAR                                 NOT NULL,
    specify_passport   BOOLEAN,
    report_template_id BIGINT,
    CONSTRAINT pk_sectionTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_SECTION_TEMPLATES UNIQUE (report_template_id, section_name),
    CONSTRAINT FK_SECTION_TEMPLATES_ON_REPORT_TEMPLATES
        FOREIGN KEY (report_template_id) REFERENCES report_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TEMPLATES
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id         BIGINT                                  NOT NULL,
    sequential_number        INTEGER                                 NOT NULL,
    title                    VARCHAR                                 NOT NULL,
    subtitle                 VARCHAR                                 NOT NULL,
    user_text_after_subtitle VARCHAR,
    section_template_id      BIGINT,
    conclusion_template_id   BIGINT,
    CONSTRAINT pk_reportProtocolTemplate PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PROTOCOL_TEMPLATES_ON_SECTION_TEMPLATES
        FOREIGN KEY (section_template_id) REFERENCES section_templates (id),
    CONSTRAINT FK_REPORT_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES
        FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS SURVEY_PROTOCOL_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id       BIGINT                                  NOT NULL,
    equipment_type_id      BIGINT                                  NOT NULL,
    title                  VARCHAR                                 NOT NULL,
    subtitle               VARCHAR                                 NOT NULL,
    conclusion_template_id BIGINT,
    CONSTRAINT pk_surveyProtocolTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_SURVEY_PROTOCOL_TEMPLATES UNIQUE (document_type_id, equipment_type_id),
    CONSTRAINT FK_SURVEY_PROTOCOL_TEMPLATES_ON_CONCLUSION_TEMPLATES
        FOREIGN KEY (conclusion_template_id) REFERENCES conclusion_templates (id)
);

CREATE TABLE IF NOT EXISTS SURVEY_PROTOCOL_DOCUMENT_HEADERS_TEMPLATES
(
    protocol_template_id BIGINT,
    document_header_id   BIGINT,
    CONSTRAINT pk_protocol_templates_of_document_header PRIMARY KEY (protocol_template_id, document_header_id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_CONTROL_TEMPLATES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id  BIGINT                                  NOT NULL,
    title             VARCHAR                                 NOT NULL,
    subtitle          VARCHAR                                 NOT NULL,
    table_template_id BIGINT,
    CONSTRAINT pk_protocolControlTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_PROTOCOL_CONTROL_TEMPLATES UNIQUE (document_type_id)
);

CREATE TABLE IF NOT EXISTS INFORMATION_CONTROL_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type_id             BIGINT                                  NOT NULL,
    sequential_number            INTEGER                                 NOT NULL,
    data_name                    VARCHAR                                 NOT NULL,
    protocol_control_template_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_informationAboutObjectOfControlTemplate PRIMARY KEY (id),
    CONSTRAINT FK_INFORMATION_CONTROL_TEMPLATES_ON_PROTOCOL_CONTROL_TEMPLATES
        FOREIGN KEY (protocol_control_template_id) REFERENCES protocol_control_templates (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_CONTROL_TEMPLATES_DOCUMENT_HEADERS
(
    protocol_template_id BIGINT,
    document_header_id   BIGINT,
    CONSTRAINT pk_protocol_control_templates_of_document_header PRIMARY KEY (protocol_template_id, document_header_id)
);

CREATE TABLE IF NOT EXISTS TABLE_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_type                   VARCHAR                                 NOT NULL,
    sequential_number            INTEGER,
    table_name                   VARCHAR,
    text_before_table            VARCHAR,
    text_after_table             VARCHAR,
    protocol_report_template_id  BIGINT,
    protocol_template_id         BIGINT,
    protocol_control_template_id BIGINT,
    CONSTRAINT pk_tableTemplate PRIMARY KEY (id),
    CONSTRAINT FK_TABLE_TEMPLATES_ON_REPORT_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_report_template_id) REFERENCES report_protocol_templates (id),
    CONSTRAINT FK_TABLE_TEMPLATES_ON_SURVEY_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_template_id) REFERENCES survey_protocol_templates (id),
    CONSTRAINT FK_TABLE_TEMPLATES_ON_PROTOCOL_CONTROL_TEMPLATES
        FOREIGN KEY (protocol_control_template_id) REFERENCES protocol_control_templates (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS_TEMPLATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number  INTEGER                                 NOT NULL,
    heading            VARCHAR                                 NOT NULL,
    column_header_type VARCHAR                                 NOT NULL,
    table_template_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_columnHeaderTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_COLUMNS_HEADERS_TEMPLATES UNIQUE (sequential_number, heading, table_template_id),
    CONSTRAINT FK_COLUMNS_HEADERS_TEMPLATES_ON_TABLE_TEMPLATES
        FOREIGN KEY (table_template_id) REFERENCES table_templates (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTION_TEMPLATES
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number            DOUBLE PRECISION                        NOT NULL,
    subsection_name              VARCHAR                                 NOT NULL,
    user_text                    VARCHAR,
    division                     VARCHAR,
    table_id                     BIGINT,
    summary_results              BOOLEAN,
    protocol_report_template_id  BIGINT,
    section_template_id          BIGINT,
    protocol_template_id         BIGINT,
    protocol_control_template_id BIGINT,
    CONSTRAINT pk_subsectionTemplate PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_TABLE_TEMPLATES FOREIGN KEY (table_id) REFERENCES table_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_REPORT_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_report_template_id) REFERENCES report_protocol_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_SECTION_TEMPLATES
        FOREIGN KEY (section_template_id) REFERENCES section_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_SURVEY_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_template_id) REFERENCES survey_protocol_templates (id),
    CONSTRAINT FK_SUBSECTION_TEMPLATES_ON_PROTOCOL_CONTROL_TEMPLATES
        FOREIGN KEY (protocol_control_template_id) REFERENCES protocol_control_templates (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATION_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    documentation_id       BIGINT                                  NOT NULL,
    sequential_number      INTEGER,
    document_name          VARCHAR                                 NOT NULL,
    subsection_template_id BIGINT,
    CONSTRAINT pk_documentationTemplate PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENTATION_TEMPLATES_ON_SUBSECTION_TEMPLATES
        FOREIGN KEY (subsection_template_id) REFERENCES subsection_templates (id)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOL_TEMPLATES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measuring_tool_id      BIGINT                                  NOT NULL,
    sequential_number      INTEGER                                 NOT NULL,
    tool                   VARCHAR                                 NOT NULL,
    model                  VARCHAR                                 NOT NULL,
    measuring_tool         VARCHAR                                 NOT NULL,
    subsection_template_id BIGINT,
    CONSTRAINT pk_measuringToolTemplate PRIMARY KEY (id),
    CONSTRAINT FK_MEASURING_TOOL_TEMPLATES_ON_SUBSECTION_TEMPLATES
        FOREIGN KEY (subsection_template_id) REFERENCES subsection_templates (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_SUBSECTION_TEMPLATES
(
    protocol_id   BIGINT,
    subsection_id BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_subsection_templates PRIMARY KEY (protocol_id, subsection_id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOL_TABLE_TEMPLATES
(
    protocol_id BIGINT,
    table_id    BIGINT,
    CONSTRAINT pk_report_protocol_templates_of_table_templates PRIMARY KEY (protocol_id, table_id)
);

CREATE TABLE IF NOT EXISTS APPENDICES_TEMPLATES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id    BIGINT                                  NOT NULL,
    name_of_list         VARCHAR                                 NOT NULL,
    sequential_number    INTEGER                                 NOT NULL,
    appendices_name      VARCHAR                                 NOT NULL,
    report_template_id   BIGINT,
    protocol_template_id BIGINT,
    CONSTRAINT pk_appendicesTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_APPENDICES_TEMPLATES UNIQUE (sequential_number, appendices_name),
    CONSTRAINT FK_APPENDICES_TEMPLATES_ON_REPORT_TEMPLATES
        FOREIGN KEY (report_template_id) REFERENCES report_templates (id),
    CONSTRAINT FK_APPENDICES_TEMPLATES_ON_SURVEY_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_template_id) REFERENCES survey_protocol_templates (id)
);

CREATE TABLE IF NOT EXISTS PAGE_TITLES
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnostic_document_id BIGINT                                  NOT NULL,
    title                  VARCHAR                                 NOT NULL,
    subtitle               VARCHAR                                 NOT NULL,
    equipment_text         VARCHAR                                 NOT NULL,
    installation_location  VARCHAR                                 NOT NULL,
    address                VARCHAR                                 NOT NULL,
    number_date            VARCHAR                                 NOT NULL,
    post                   VARCHAR                                 NOT NULL,
    initials               VARCHAR                                 NOT NULL,
    city                   VARCHAR                                 NOT NULL,
    year                   VARCHAR                                 NOT NULL,
    CONSTRAINT pk_pageTitle PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_HEADERS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    division_type       VARCHAR                                 NOT NULL,
    division            VARCHAR                                 NOT NULL,
    address             VARCHAR,
    certificate         VARCHAR,
    contacts            VARCHAR,
    page_title_id       BIGINT,
    survey_protocol_id  BIGINT,
    protocol_control_id BIGINT,
    CONSTRAINT pk_documentHeader PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENT_HEADERS_ON_PAGE_TITLES FOREIGN KEY (page_title_id) REFERENCES page_titles (id)
);

CREATE TABLE IF NOT EXISTS WORK_PLACES
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch    VARCHAR                                 NOT NULL,
    placeWork VARCHAR                                 NOT NULL,
    address   VARCHAR                                 NOT NULL,
    CONSTRAINT pk_workplace PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CONCLUSIONS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    positive_text VARCHAR                                 NOT NULL,
    negative_text VARCHAR                                 NOT NULL,
    CONSTRAINT pk_conclusion PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS SURVEY_PROTOCOLS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnostic_document_id BIGINT                                  NOT NULL,
    work_place_id          BIGINT                                  NOT NULL,
    title                  VARCHAR                                 NOT NULL,
    subtitle               VARCHAR                                 NOT NULL,
    conclusion_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_surveyProtocol PRIMARY KEY (id),
    CONSTRAINT FK_SURVEY_PROTOCOL_ON_CONCLUSION_TEMPLATES FOREIGN KEY (conclusion_id) REFERENCES conclusions (id),
    CONSTRAINT FK_SURVEY_PROTOCOL_ON_WORK_PLACES FOREIGN KEY (work_place_id) REFERENCES work_places (id)
);

CREATE TABLE IF NOT EXISTS PROTOCOL_CONTROLS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnostic_document_id BIGINT                                  NOT NULL,
    work_place_id          BIGINT,
    title                  VARCHAR                                 NOT NULL,
    subtitle               VARCHAR                                 NOT NULL,
    CONSTRAINT pk_protocolControl PRIMARY KEY (id),
    CONSTRAINT FK_PROTOCOL_CONTROLS_ON_WORK_PLACES FOREIGN KEY (work_place_id) REFERENCES work_places (id)
);

CREATE TABLE IF NOT EXISTS INFORMATION_OBJECT_CONTROL
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id         BIGINT                                  NOT NULL,
    sequential_number   INTEGER                                 NOT NULL,
    data_name           VARCHAR,
    data_value          VARCHAR                                 NOT NULL,
    protocol_control_id BIGINT,
    CONSTRAINT pk_informationAboutObjectOfControl PRIMARY KEY (id),
    CONSTRAINT FK_INFORMATION_OBJECT_CONTROL_ON_PROTOCOL_CONTROLS
        FOREIGN KEY (protocol_control_id) REFERENCES protocol_controls (id)
);

CREATE TABLE IF NOT EXISTS REPORTS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnostic_document_id BIGINT                                  NOT NULL,
    page_title_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_ON_PAGE_TITLE
        FOREIGN KEY (page_title_id) REFERENCES page_titles (id)
);

CREATE TABLE IF NOT EXISTS APPENDICES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number  INTEGER                                 NOT NULL,
    appendices_name    VARCHAR                                 NOT NULL,
    report_id          BIGINT,
    survey_protocol_id BIGINT,
    CONSTRAINT pk_appendices PRIMARY KEY (id),
    CONSTRAINT FK_APPENDICES_ON_REPORTS FOREIGN KEY (report_id) REFERENCES reports (id),
    CONSTRAINT FK_APPENDICES_ON_SURVEY_PROTOCOLS
        FOREIGN KEY (survey_protocol_id) REFERENCES survey_protocols (id)
);

CREATE TABLE IF NOT EXISTS SECTIONS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER                                 NOT NULL,
    section_name      VARCHAR                                 NOT NULL,
    report_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_section PRIMARY KEY (id),
    CONSTRAINT FK_SECTION_ON_REPORTS FOREIGN KEY (report_id) REFERENCES reports (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PROTOCOLS
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number        INTEGER                                 NOT NULL,
    title                    VARCHAR                                 NOT NULL,
    subtitle                 VARCHAR                                 NOT NULL,
    user_text_after_subtitle VARCHAR,
    section_id               BIGINT,
    conclusion_id            BIGINT,
    CONSTRAINT pk_reportProtocol PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PROTOCOLS_ON_SECTIONS FOREIGN KEY (section_id) REFERENCES sections (id),
    CONSTRAINT FK_REPORT_PROTOCOL_TEMPLATES_ON_CONCLUSIONS
        FOREIGN KEY (conclusion_id) REFERENCES conclusions (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_TABLES
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_type          VARCHAR                                 NOT NULL,
    sequential_number   INTEGER,
    table_name          VARCHAR,
    text_before_table   VARCHAR,
    text_after_table    VARCHAR,
    protocol_report_id  BIGINT,
    survey_protocol_id  BIGINT,
    protocol_control_id BIGINT,
    CONSTRAINT pk_documentTable PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENT_TABLES_ON_REPORT_PROTOCOL_TEMPLATES
        FOREIGN KEY (protocol_report_id) REFERENCES report_protocols (id),
    CONSTRAINT FK_DOCUMENT_TABLES_ON_SURVEY_PROTOCOLS
        FOREIGN KEY (survey_protocol_id) REFERENCES survey_protocols (id),
    CONSTRAINT FK_DOCUMENT_TABLES_ON_PROTOCOL_CONTROLS
        FOREIGN KEY (protocol_control_id) REFERENCES protocol_controls (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS_HEADERS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number  INTEGER                                 NOT NULL,
    heading            VARCHAR                                 NOT NULL,
    column_header_type VARCHAR                                 NOT NULL,
    table_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_columnHeader PRIMARY KEY (id),
    CONSTRAINT FK_COLUMNS_HEADERS_ON_DOCUMENT_TABLES FOREIGN KEY (table_id) REFERENCES document_tables (id)
);

CREATE TABLE IF NOT EXISTS CELLS_TABLES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    merge_lines   INTEGER,
    column_number INTEGER                                 NOT NULL,
    string_number INTEGER                                 NOT NULL,
    cell_value    VARCHAR                                 NOT NULL,
    table_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_cellTable PRIMARY KEY (id),
    CONSTRAINT FK_CELL_TABLES_ON_DOCUMENT_TABLES FOREIGN KEY (table_id) REFERENCES document_tables (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_EQUIPMENT_PASSPORTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number  VARCHAR                                 NOT NULL,
    header             VARCHAR                                 NOT NULL,
    meaning            VARCHAR                                 NOT NULL,
    section_id         BIGINT,
    survey_protocol_id BIGINT,
    CONSTRAINT pk_documentEquipmentPassport PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENT_EQUIPMENT_PASSPORTS_ON_SECTIONS FOREIGN KEY (section_id) REFERENCES sections (id),
    CONSTRAINT FK_DOCUMENT_EQUIPMENT_PASSPORTS_ON_SURVEY_PROTOCOLS
        FOREIGN KEY (survey_protocol_id) REFERENCES survey_protocols (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTIONS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number   INTEGER                                 NOT NULL,
    subsection_name     VARCHAR                                 NOT NULL,
    user_text           VARCHAR,
    division            VARCHAR,
    table_id            BIGINT,
    protocol_report_id  BIGINT,
    section_id          BIGINT,
    survey_protocol_id  BIGINT,
    protocol_control_id BIGINT,
    CONSTRAINT pk_subsection PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTIONS_ON_DOCUMENT_TABLES FOREIGN KEY (table_id) REFERENCES document_tables (id),
    CONSTRAINT FK_SUBSECTIONS_ON_REPORT_PROTOCOLS FOREIGN KEY (protocol_report_id) REFERENCES report_protocols (id),
    CONSTRAINT FK_SUBSECTIONS_ON_SECTIONS FOREIGN KEY (section_id) REFERENCES sections (id),
    CONSTRAINT FK_SUBSECTION_ON_SURVEY_PROTOCOL_TEMPLATES
        FOREIGN KEY (survey_protocol_id) REFERENCES survey_protocols (id),
    CONSTRAINT FK_SUBSECTIONS_ON_PROTOCOL_CONTROLS FOREIGN KEY (protocol_control_id) REFERENCES protocol_controls (id)
);

CREATE TABLE IF NOT EXISTS REGULATORY_DOCUMENTATIONS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER,
    document_name     VARCHAR                                 NOT NULL,
    subsection_id     BIGINT,
    CONSTRAINT pk_regulatoryDocumentation PRIMARY KEY (id),
    CONSTRAINT FK_REGULATORY_DOCUMENTATIONS_ON_SUBSECTIONS FOREIGN KEY (subsection_id) REFERENCES subsections (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENT_MEASURING_TOOLS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequential_number INTEGER,
    measuring_tool    VARCHAR                                 NOT NULL,
    subsection_id     BIGINT,
    CONSTRAINT pk_documentMeasuringTool PRIMARY KEY (id),
    CONSTRAINT FK_MEASURING_TOOL_ON_SUBSECTIONS FOREIGN KEY (subsection_id) REFERENCES subsections (id)
);