CREATE TABLE IF NOT EXISTS DIAGNOSTIC_EQUIPMENT_DATA
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id BIGINT                                  NOT NULL,
    equipment_id      BIGINT                                  NOT NULL,
    volume            INTEGER,
    equipment_full    BOOLEAN,
    equipment_old     BOOLEAN,
    geodesy_locations INTEGER,
    CONSTRAINT pk_diagnosticEquipmentData PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_ELEMENT_DATA
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_type_id              BIGINT                                  NOT NULL,
    part_element_type_id         BIGINT,
    element_id                   BIGINT                                  NOT NULL,
    part_element_id              BIGINT,
    element_name                 VARCHAR                                 NOT NULL,
    part_element_name            VARCHAR,
    design_thickness             DOUBLE PRECISION,
    outer_diameter               INTEGER,
    min_diameter                 INTEGER,
    max_diameter                 INTEGER,
    diagnostic_equipment_data_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_elementData PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENT_ELEMENT_DATA_ON_DIAGNOSTIC_EQUIPMENT_DATA FOREIGN KEY (diagnostic_equipment_data_id)
        REFERENCES diagnostic_equipment_data (id)
);

CREATE TABLE IF NOT EXISTS DEFECTS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    defect_name             VARCHAR                                 NOT NULL,
    not_meet_requirements   BOOLEAN                                 NOT NULL,
    calculation             VARCHAR                                 NOT NULL,
    use_calculate_thickness BOOLEAN,
    CONSTRAINT pk_defect PRIMARY KEY (id),
    CONSTRAINT UQ_DEFECTS UNIQUE (defect_name)
);

CREATE TABLE IF NOT EXISTS ELEMENT_REPAIRS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    repair_name VARCHAR                                 NOT NULL,
    calculation VARCHAR                                 NOT NULL,
    CONSTRAINT pk_elementRepair PRIMARY KEY (id),
    CONSTRAINT UQ_ELEMENT_REPAIRS UNIQUE (repair_name)
);

CREATE TABLE IF NOT EXISTS MEASUREMENTS_PARAMETERS
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parameter_name   VARCHAR                                 NOT NULL,
    unit_measurement VARCHAR                                 NOT NULL,
    calculation      VARCHAR                                 NOT NULL,
    defect_id        BIGINT,
    repair_id        BIGINT,
    CONSTRAINT pk_measuredParameter PRIMARY KEY (id),
    CONSTRAINT FK_MEASUREMENTS_PARAMETERS_ON_DEFECTS FOREIGN KEY (defect_id) REFERENCES defects (id),
    CONSTRAINT FK_MEASUREMENTS_PARAMETERS_ON_ELEMENT_REPAIRS FOREIGN KEY (repair_id) REFERENCES element_repairs (id)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_THICKNESS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id  BIGINT                                  NOT NULL,
    element_id         BIGINT                                  NOT NULL,
    part_element_id    BIGINT,
    diameter           INTEGER,
    min_thickness      DOUBLE PRECISION,
    acceptable_percent INTEGER,
    measurement_error  FLOAT,
    CONSTRAINT pk_acceptableThickness PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_HARDNESS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id       BIGINT                                  NOT NULL,
    element_id              BIGINT                                  NOT NULL,
    part_element_id         BIGINT,
    min_allowable_diameter  INTEGER,
    min_allowable_thickness FLOAT,
    min_hardness            INTEGER                                 NOT NULL,
    max_hardness            INTEGER                                 NOT NULL,
    measurement_error       FLOAT,
    CONSTRAINT pk_acceptableHardness PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ACCEPTABLE_DEVIATIONS_GEODESY
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id                 BIGINT                                  NOT NULL,
    fulls                             BOOLEAN                                 NOT NULL,
    old                               BOOLEAN                                 NOT NULL,
    volume                            INTEGER                                 NOT NULL,
    acceptable_precipitation          INTEGER                                 NOT NULL,
    max_difference_neighboring_points INTEGER                                 NOT NULL,
    max_difference_diametric_points   INTEGER                                 NOT NULL,
    CONSTRAINT pk_permissibleDeviationsGeodesy PRIMARY KEY (id),
    CONSTRAINT UQ_PERMISSIBLE_DEVIATIONS_GEODESY UNIQUE (equipment_type_id, fulls, old)
);

CREATE TABLE IF NOT EXISTS GEODESIC_MEASUREMENTS_POINTS
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_journal_id             BIGINT                                  NOT NULL,
    equipment_id                BIGINT                                  NOT NULL,
    sequential_number           INTEGER                                 NOT NULL,
    number_measurement_location INTEGER                                 NOT NULL,
    reference_point_value       INTEGER,
    control_point_value         INTEGER                                 NOT NULL,
    transition_value            INTEGER,
    CONSTRAINT pk_geodesicMeasurementsPoint PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_GEODESIC_MEASUREMENTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipmentGeodesicMeasurements PRIMARY KEY (id),
    CONSTRAINT UQ_EQUIPMENT_GEODESIC_MEASUREMENTS UNIQUE (equipment_id)
);

CREATE TABLE IF NOT EXISTS REFERENCE_POINTS
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    geodesic_measurement_id  BIGINT                                  NOT NULL,
    place_number             INTEGER                                 NOT NULL,
    calculated_height        INTEGER                                 NOT NULL,
    deviation                INTEGER                                 NOT NULL,
    precipitation            INTEGER,
    acceptable_precipitation BOOLEAN,
    result_measurement_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_referencePoint PRIMARY KEY (id),
    CONSTRAINT FK_REFERENCE_POINTS_ON_EQUIPMENT_GEODESIC_MEASUREMENTS
        FOREIGN KEY (geodesic_measurement_id) REFERENCES equipment_geodesic_measurements (id)
);

CREATE TABLE IF NOT EXISTS DEVIATION_YEARS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_point_id BIGINT                                  NOT NULL,
    year               INTEGER                                 NOT NULL,
    deviation          INTEGER                                 NOT NULL,
    CONSTRAINT pk_deviationYear PRIMARY KEY (id),
    CONSTRAINT UQ_DEVIATION_YEARS UNIQUE (reference_point_id, year),
    CONSTRAINT FK_DEVIATION_YEARS_ON_REFERENCE_POINTS FOREIGN KEY (reference_point_id) REFERENCES reference_points (id)
);

CREATE TABLE IF NOT EXISTS CONTROL_POINTS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    geodesic_measurement_id BIGINT                                  NOT NULL,
    place_number            INTEGER                                 NOT NULL,
    calculated_height       INTEGER                                 NOT NULL,
    deviation               INTEGER                                 NOT NULL,
    measurement_id          BIGINT                                  NOT NULL,
    result_measurement_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_controlPoint PRIMARY KEY (id),
    CONSTRAINT FK_CONTROL_POINTS_ON_EQUIPMENT_GEODESIC_MEASUREMENTS
        FOREIGN KEY (geodesic_measurement_id) REFERENCES equipment_geodesic_measurements (id)
);

CREATE TABLE IF NOT EXISTS POINTS_DIFFERENCE
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    geodesic_measurement_id BIGINT                                  NOT NULL,
    type                    VARCHAR                                 NOT NULL,
    first_place_number      INTEGER                                 NOT NULL,
    second_place_number     INTEGER                                 NOT NULL,
    difference              INTEGER                                 NOT NULL,
    acceptable_difference   BOOLEAN,
    result_measurement_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_pointDifference PRIMARY KEY (id),
    CONSTRAINT FK_POINTS_DIFFERENCE_ON_EQUIPMENT_GEODESIC_MEASUREMENTS
        FOREIGN KEY (geodesic_measurement_id) REFERENCES equipment_geodesic_measurements (id)
);

CREATE TABLE IF NOT EXISTS VISUAL_MEASURING_SURVEYS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id BIGINT                                  NOT NULL,
    element_id   BIGINT                                  NOT NULL,
    element_name VARCHAR                                 NOT NULL,
    inspection   VARCHAR,
    CONSTRAINT pk_visualMeasuringSurvey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EXAMINED_PARTS_ELEMENT
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_element_id            BIGINT                                  NOT NULL,
    part_element_name          VARCHAR                                 NOT NULL,
    inspection                 VARCHAR                                 NOT NULL,
    visual_measuring_survey_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_examinedPartElement PRIMARY KEY (id),
    CONSTRAINT FK_EXAMINED_PARTS_ELEMENT_ON_VISUAL_MEASURING_SURVEYS
        FOREIGN KEY (visual_measuring_survey_id) REFERENCES visual_measuring_surveys (id)
);

CREATE TABLE IF NOT EXISTS IDENTIFIED_DEFECTS
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    defect_id                  BIGINT                                  NOT NULL,
    welded_joint_number        INTEGER,
    defect_name                VARCHAR                                 NOT NULL,
    not_meet_requirements      BOOLEAN                                 NOT NULL,
    use_calculate_thickness    BOOLEAN                                 NOT NULL,
    examined_part_element_id   BIGINT,
    visual_measuring_survey_id BIGINT,
    CONSTRAINT pk_identifiedDefect PRIMARY KEY (id),
    CONSTRAINT FK_IDENTIFIED_DEFECTS_ON_EXAMINED_PARTS_ELEMENT
        FOREIGN KEY (examined_part_element_id) REFERENCES examined_parts_element (id),
    CONSTRAINT FK_IDENTIFIED_DEFECTS_ON_VISUAL_MEASURING_SURVEYS
        FOREIGN KEY (visual_measuring_survey_id) REFERENCES visual_measuring_surveys (id)
);

CREATE TABLE IF NOT EXISTS COMPLETED_REPAIRS
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    repair_id                  BIGINT                                  NOT NULL,
    repair_name                VARCHAR                                 NOT NULL,
    examined_part_element_id   BIGINT,
    visual_measuring_survey_id BIGINT,
    CONSTRAINT pk_completedRepair PRIMARY KEY (id),
    CONSTRAINT FK_COMPLETED_REPAIRS_ON_EXAMINED_PARTS_ELEMENT
        FOREIGN KEY (examined_part_element_id) REFERENCES examined_parts_element (id),
    CONSTRAINT FK_COMPLETED_REPAIRS_ON_VISUAL_MEASURING_SURVEYS
        FOREIGN KEY (visual_measuring_survey_id) REFERENCES visual_measuring_surveys (id)
);

CREATE TABLE IF NOT EXISTS PARAMETER_MEASUREMENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_number INTEGER                                 NOT NULL,
    parameter_number   INTEGER                                 NOT NULL,
    parameter_name     VARCHAR                                 NOT NULL,
    min_value          DOUBLE PRECISION                        NOT NULL,
    max_value          DOUBLE PRECISION,
    unit_measurement   VARCHAR                                 NOT NULL,
    defect_id          BIGINT,
    repair_id          BIGINT,
    CONSTRAINT pk_parameterMeasurement PRIMARY KEY (id),
    CONSTRAINT FK_PARAMETER_MEASUREMENTS_ON_IDENTIFIED_DEFECTS FOREIGN KEY (defect_id) REFERENCES identified_defects (id),
    CONSTRAINT FK_PARAMETER_MEASUREMENTS_ON_COMPLETED_REPAIRS FOREIGN KEY (repair_id) REFERENCES completed_repairs (id)
);

CREATE TABLE IF NOT EXISTS UT_MEASUREMENTS
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diameter              INTEGER,
    measurement_number    INTEGER,
    min_measurement_value DOUBLE PRECISION                        NOT NULL,
    max_measurement_value DOUBLE PRECISION                        NOT NULL,
    max_corrosion         DOUBLE PRECISION,
    residual_thickness    DOUBLE PRECISION                        NOT NULL,
    min_acceptable_value  DOUBLE PRECISION,
    validity              VARCHAR                                 NOT NULL,
    acceptable            BOOLEAN,
    invalid               BOOLEAN,
    approaching_invalid   BOOLEAN,
    reached_invalid       BOOLEAN,
    no_standard           BOOLEAN,
    CONSTRAINT pk_ultrasonicThicknessMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UT_ELEMENTS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id   BIGINT                                  NOT NULL,
    element_id     BIGINT                                  NOT NULL,
    element_name   VARCHAR                                 NOT NULL,
    measurement_id BIGINT,
    CONSTRAINT pk_ultrasonicThicknessElementMeasurement PRIMARY KEY (id),
    CONSTRAINT FK_UT_ELEMENT_ON_UT_MEASUREMENTS FOREIGN KEY (measurement_id) REFERENCES ut_measurements (id)
);

CREATE TABLE IF NOT EXISTS UT_PARTS_ELEMENTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_element_id   BIGINT                                  NOT NULL,
    part_element_name VARCHAR                                 NOT NULL,
    measurement_id    BIGINT                                  NOT NULL,
    element_id        BIGINT,
    CONSTRAINT pk_ultrasonicThicknessPartElementMeasurement PRIMARY KEY (id),
    CONSTRAINT FK_UT_PARTS_ELEMENTS_ON_UT_MEASUREMENTS FOREIGN KEY (measurement_id) REFERENCES ut_measurements (id),
    CONSTRAINT FK_UT_PARTS_ELEMENTS_ON_UT_ELEMENTS FOREIGN KEY (element_id) REFERENCES ut_elements (id)
);

CREATE TABLE IF NOT EXISTS HARDNESS_MEASUREMENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nominal_size       INTEGER,
    measurement_number INTEGER,
    measurement_value  DOUBLE PRECISION                        NOT NULL,
    validity           VARCHAR                                 NOT NULL,
    validity_value     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_hardnessMeasurement PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HARDNESS_ELEMENTS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id   BIGINT                                  NOT NULL,
    element_id     BIGINT                                  NOT NULL,
    element_name   VARCHAR                                 NOT NULL,
    measurement_id BIGINT,
    CONSTRAINT pk_elementHardnessMeasurement PRIMARY KEY (id),
    CONSTRAINT FK_HARDNESS_ELEMENTS_ON_HARDNESS_MEASUREMENTS
        FOREIGN KEY (measurement_id) REFERENCES hardness_measurements (id)
);

CREATE TABLE IF NOT EXISTS HARDNESS_PARTS_ELEMENTS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_element_id   BIGINT                                  NOT NULL,
    part_element_name VARCHAR                                 NOT NULL,
    measurement_id    BIGINT                                  NOT NULL,
    element_id        BIGINT,
    CONSTRAINT pk_partElementHardnessMeasurement PRIMARY KEY (id),
    CONSTRAINT FK_HARDNESS_PARTS_ELEMENTS_ON_HARDNESS_MEASUREMENTS
        FOREIGN KEY (measurement_id) REFERENCES hardness_measurements (id),
    CONSTRAINT FK_HARDNESS_PARTS_ELEMENTS_ON_HARDNESS_ELEMENTS
        FOREIGN KEY (element_id) REFERENCES hardness_elements (id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_EMPLOYEE
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id   BIGINT                                  NOT NULL,
    recommendation VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendationEmployee PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ULTRASONIC_CONTROLS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work_journal_id     BIGINT                                  NOT NULL,
    standard_size       VARCHAR                                 NOT NULL,
    welded_joint_number INTEGER,
    measurement         VARCHAR                                 NOT NULL,
    estimation          VARCHAR                                 NOT NULL,
    CONSTRAINT pk_ultrasonicControl PRIMARY KEY (id)
);