CREATE TABLE IF NOT EXISTS DIAGNOSTIC_DOCUMENT_TYPES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR                                 NOT NULL,
    subtitle      VARCHAR                                 NOT NULL,
    type_document VARCHAR                                 NOT NULL,
    CONSTRAINT pk_diagnosticDocumentType PRIMARY KEY (id),
    CONSTRAINT UQ_DIAGNOSTIC_DOCUMENT_TYPES UNIQUE (title, subtitle, type_document)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATIONS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    view   VARCHAR,
    number VARCHAR,
    title  VARCHAR                                 NOT NULL,
    path   VARCHAR,
    CONSTRAINT pk_documentation PRIMARY KEY (id),
    CONSTRAINT UQ_DOCUMENTATIONS UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS LABORATORY_EMPLOYEES
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    post        VARCHAR                                 NOT NULL,
    initials    VARCHAR                                 NOT NULL,
    CONSTRAINT pk_laboratoryEmployee PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_CERTIFICATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type      VARCHAR                                 NOT NULL,
    certificate_number VARCHAR                                 NOT NULL,
    control_type       VARCHAR                                 NOT NULL,
    level              VARCHAR                                 NOT NULL,
    start_date         DATE                                    NOT NULL,
    end_date           DATE                                    NOT NULL,
    points             VARCHAR                                 NOT NULL,
    organization       VARCHAR                                 NOT NULL,
    employee_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_employeeCertificate PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEE_CERTIFICATES UNIQUE (control_type, employee_id),
    CONSTRAINT FK_EMPLOYEE_CERTIFICATES_ON_LABORATORY_EMPLOYEES
        FOREIGN KEY (employee_id) REFERENCES laboratory_employees (id)
);

CREATE TABLE IF NOT EXISTS LABORATORY_CERTIFICATES
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    division_id    BIGINT                                  NOT NULL,
    document_type  VARCHAR                                 NOT NULL,
    license_number VARCHAR                                 NOT NULL,
    start_date     DATE                                    NOT NULL,
    end_date       DATE                                    NOT NULL,
    organization   VARCHAR                                 NOT NULL,
    CONSTRAINT pk_laboratoryCertificate PRIMARY KEY (id),
    CONSTRAINT UQ_LABORATORY_CERTIFICATES UNIQUE (document_type, license_number, start_date, end_date)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOLS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    toll                   VARCHAR                                 NOT NULL,
    model                  VARCHAR                                 NOT NULL,
    work_number            VARCHAR,
    purpose                VARCHAR,
    manufacturing          DATE,
    exploitation           DATE,
    manufacturer           VARCHAR,
    measuring_range        VARCHAR,
    characteristics        VARCHAR,
    owner                  VARCHAR                                 NOT NULL,
    verification_date      DATE,
    next_verification_date DATE,
    organization           VARCHAR,
    certificate_number     VARCHAR,
    registry               VARCHAR,
    note                   VARCHAR,
    control_type           VARCHAR                                 NOT NULL,
    laboratory_employee_id BIGINT,
    CONSTRAINT pk_measuringTool PRIMARY KEY (id),
    CONSTRAINT UQ_MEASURING_TOOL UNIQUE (toll, model, work_number)
);

CREATE TABLE IF NOT EXISTS WORK_JOURNAL
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type_id   BIGINT,
    equipment_id        BIGINT,
    date                DATE                                    NOT NULL,
    branch              VARCHAR                                 NOT NULL,
    place_work          VARCHAR                                 NOT NULL,
    address             VARCHAR                                 NOT NULL,
    equipment_diagnosed VARCHAR                                 NOT NULL,
    work_type           VARCHAR                                 NOT NULL,
    task_source         VARCHAR,
    comment             VARCHAR,
    chief_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_workJournal PRIMARY KEY (id),
    CONSTRAINT FK_WORK_JOURNAL_ON_LABORATORY_EMPLOYEES FOREIGN KEY (chief_id) REFERENCES laboratory_employees (id)
);

CREATE TABLE IF NOT EXISTS JOURNAL_EMPLOYEES
(
    journal_id  BIGINT,
    employee_id BIGINT,
    CONSTRAINT pk_tasks_journal_of_laboratory_employees PRIMARY KEY (journal_id, employee_id)
);

CREATE TABLE IF NOT EXISTS DIAGNOSTIC_DOCUMENTS
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_id                BIGINT                                  NOT NULL,
    work_journal_id             BIGINT                                  NOT NULL,
    date                        DATE                                    NOT NULL,
    branch                      VARCHAR                                 NOT NULL,
    place_work                  VARCHAR                                 NOT NULL,
    diagnostic_document_type_id BIGINT                                  NOT NULL,
    document_number             INTEGER                                 NOT NULL,
    next_date                   DATE,
    status                      VARCHAR                                 NOT NULL,
    document_path               VARCHAR,
    drawing_path                VARCHAR,
    CONSTRAINT pk_diagnosticDocument PRIMARY KEY (id),
    CONSTRAINT UQ_DIAGNOSTIC_DOCUMENT UNIQUE (equipment_id, date),
    CONSTRAINT FK_DIAGNOSTIC_DOCUMENT_ON_DIAGNOSTIC_DOCUMENT_TYPES
        FOREIGN KEY (diagnostic_document_type_id) REFERENCES diagnostic_document_types (id),
    CONSTRAINT FK_DIAGNOSTIC_DOCUMENTS_ON_WORK_JOURNAL FOREIGN KEY (work_journal_id) REFERENCES work_journal (id)
);

CREATE TABLE IF NOT EXISTS REMARKS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    remark             VARCHAR                                 NOT NULL,
    document_id        BIGINT                                  NOT NULL,
    employee_id        BIGINT                                  NOT NULL,
    initials           VARCHAR                                 NOT NULL,
    document_corrected BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_remark PRIMARY KEY (id),
    CONSTRAINT FK_REMARKS_ON_DIAGNOSTIC_DOCUMENTS FOREIGN KEY (document_id) REFERENCES diagnostic_documents (id)
);
