package ru.nabokovsg.documentNK.model.template.common;

public enum ColumnHeaderType {

    STRING_NUMBER,
    DATE,
    SURVEYS_DESCRIPTION,
    ORGANIZATION_NAME,
    REPAIR_DESCRIPTION,
    DOCUMENT_NUMBER,
    ELEMENT,
    PART_ELEMENT,
    DEFECTS,
    REPAIR_ELEMENT,
    VISUAL_INSPECTION,
    DESIGN_THICKNESS,
    MEASURED_THICKNESS,
    MAX_CORROSION,
    RESIDUAL_THICKNESS,
    MIN_ALLOWABLE_THICKNESS,
    PLACE_NUMBER,
    HEIGHT,
    DEVIATION,
    PRECIPITATION,
    DIFFERENCE_NEIGHBORING_POINTS,
    DIFFERENCE_DIAMETRICAL_POINTS,
    DIAMETER,
    HARDNESS
}